name: pr10
on: push
jobs:
  start:
    runs-on: windows-latest
    steps:
      - name: Checkou
        uses: actions/checkout@v5.0.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' 

      - name: Step2
        run: dotnet run --project ./pr10.csproj